// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWuz0vKv_aAv8LzJEXyVNRilh8rhjH7AU',
    appId: '1:789024738939:web:2a4ab7c1dd98cd86591cde',
    messagingSenderId: '789024738939',
    projectId: 'robot-optica',
    authDomain: 'robot-optica.firebaseapp.com',
    storageBucket: 'robot-optica.firebasestorage.app',
    measurementId: 'G-Z3E02HYRLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByo_wgoEqQk5qV_tbUFS0uI7Xu-j0tG2g',
    appId: '1:789024738939:android:437f2bf57d09cfb8591cde',
    messagingSenderId: '789024738939',
    projectId: 'robot-optica',
    storageBucket: 'robot-optica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfUkOt7bUQBbuPlYyWm4RPXILziqc8ATk',
    appId: '1:789024738939:ios:d314fabf338781b9591cde',
    messagingSenderId: '789024738939',
    projectId: 'robot-optica',
    storageBucket: 'robot-optica.firebasestorage.app',
    iosBundleId: 'com.example.robotOptica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfUkOt7bUQBbuPlYyWm4RPXILziqc8ATk',
    appId: '1:789024738939:ios:d314fabf338781b9591cde',
    messagingSenderId: '789024738939',
    projectId: 'robot-optica',
    storageBucket: 'robot-optica.firebasestorage.app',
    iosBundleId: 'com.example.robotOptica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWuz0vKv_aAv8LzJEXyVNRilh8rhjH7AU',
    appId: '1:789024738939:web:395b91529565943a591cde',
    messagingSenderId: '789024738939',
    projectId: 'robot-optica',
    authDomain: 'robot-optica.firebaseapp.com',
    storageBucket: 'robot-optica.firebasestorage.app',
    measurementId: 'G-RGKNBKZ1Q9',
  );
}
